# Generated by Django 2.2.1 on 2019-08-31 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tds_site', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Links',
            new_name='Link',
        ),
    ]
