# Generated by Django 2.2.1 on 2019-09-01 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tds_site', '0004_auto_20190901_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkpref',
            name='weight',
            field=models.FloatField(),
        ),
        migrations.AlterUniqueTogether(
            name='link',
            unique_together={('link',)},
        ),
    ]
