# Generated by Django 2.2.1 on 2019-09-11 20:07

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tds_site', '0007_auto_20190908_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkpref',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
